[package]
name = "kham-capi"
description = "C FFI bindings for the kham Thai word segmenter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
kham-core = { workspace = true, features = ["std"] }

[build-dependencies]
cbindgen = "0.26"
